### PR TITLE
Add support for positional params in `start_fn` and `finish_fn`

### PR DESCRIPTION
**Pull request by Veetaha**
Partially addresses https://github.com/elastio/bon/issues/24.

It's now possible to add `#[builder(start_fn/finish_fn)]` to the members to mark them as positional arguments to the `start_fn/finish_fn` respectively.

The relative order of members with `#[builder(start_fn/finish_fn)]` matters. Such that all members with `start_fn` will go in the same order as they are declared relative to each other in the start function, and all members with `finish_fn` will go in the same order as they are declared relative to each other in the finishing method.

For anyone willing to test this feature right from the oven, use this in `Cargo.toml`:
```toml
bon = { git = "https://github.com/elastio/bon", branch = "feat/positional-only-members" }
```

Here are some tests that showcase the API:

https://github.com/elastio/bon/blob/be3c9823e4181cfd7db2fde82f04f868a89a687b/bon/tests/integration/builder/positional_members.rs#L19-L145

This is still a draft that I'm planning to finish by the end of the week. Remaining work:
- [x] Add start fn args into builder's debug output and Clone derive
- [x] Enforce the order: start_fn params, finish_fn params, and then named/skipped params in any order (this way the order of evaluation of skip/default expressions and the variables available in their scope is consistent with the order of declaration)
- [x] Add more exhaustive tests, update existing ones, validate edge cases
- [x] Update the API reference documentation on the website
- [x] Add a new page to the Guide documentation on the website
- [x] (Maybe post-merge) start a blog post for the next minor release
- [ ] Self-review and post-refactoring

### CODE REVIEW

**Comment by Veetaha** [comment]
cc @EdJoPaTo, @dzmitry-lahoda, and @ThomasAlban. I'd be glad to hear your feedback around this design, maybe you'd have any ideas for some better syntax to express this.

**Comment by ThomasAlban** [comment]
First of all, thank you very much for all your work on this crate!
I definitely prefer the
```rust
#[builder(start_fn)]
#[builder(finish_fn)]
```
over what is currently available. However, supplying fields as args to finish_fn is something I can't see myself ever using, I was more hoping for a single toggle at the top of the struct or fn which toggles every required field to be an arg to the start function. I was also hoping this would mean there would be no need for the finish_fn, further reducing the verbosity of the API. 
I realise sacrificing the finish_fn also removes the ability to check you haven't called any optional functions multiple times, but I don't think this matters as logically it makes sense that the final call is the value that is used anyway.
Let me know if there are any reasons why supplying args to finish_fn would be useful as I can't see any!

**Comment by Veetaha** [comment]
>  I was more hoping for a single toggle at the top of the struct or fn which toggles every required field to be an arg to the start function.

Yeah, that's why this PR "partially addresses #24" (as written at the top of the PR description)

> Let me know if there are any reasons why supplying args to finish_fn would be useful as I can't see any!

I do think it's useful. For example an API for sending messages from one person to another

```rust
#[derive(bon::Builder)]
#[builder(start_fn = from, finish_fn = to, on(String, into))]
struct Message {
    #[builder(pos = start_fn)]
    sender: String,

    body: String,
    is_urgent: bool,

    #[builder(pos = finish_fn)]
    recipient: String,
}

let message = Message::from("Blackjack")
    .body("Hello, Bon!")
    .is_urgent(true)
    .to("Bon");
```

Another use case is the API similar to [sqlx](https://docs.rs/sqlx/latest/sqlx/macro.query.html):

```rust
let account = sqlx::query!("select (1) as id, 'Herp Derpinson' as name")
    .fetch_one(&mut conn)
    .await?;
```
Here you need to pass the DB connection object as an argument of the finishing method (i.e. where you'd like to fetch from).

**Comment by ThomasAlban** [comment]
Ah yes I hadn't considered how it allows you to force an order in your API. Yeah, makes perfect sense and I retract my previous statement! 
Do you plan on adding something more like a single toggle to reduce API verbosity?

**Comment by Veetaha** [comment]
> I definitely prefer the
> ```rust
> #[builder(start_fn)]
> #[builder(finish_fn)]
> ```

Now I think this notation isn't obvious enough. Maybe this is easier to read:
```rust
#[builder(arg = start_fn)]
#[builder(arg = finish_fn)]
```

**Comment by Veetaha** [comment]
I don't really see a nice syntax for this. The one that sucks less I think is
```
#[builder(source = start_fn)]
#[builder(source = finish_fn)]
```
Which delivers the semantic meaning of "where the value for this member comes from"

**Comment by ThomasAlban** [comment]
Could do 'src' instead of 'source' to make it more concise?

**Comment by Veetaha** [comment]
Yeah, I just can't decide. Now that you put it that way, it seems logical. Glad I can put the blame of naming on someone else 🐱 . Be it `#[builder(start_fn/finish_fn)]`

**Comment by EdJoPaTo** [comment]
I think I prefer `#[builder(on_start_fn)]` to be a bit more clear what is meant from just reading some code someone else write without knowing bon details.

The key=value doesn’t seem to add much helpful context, might suggest more values and is longer so I think having only the keyword is a good choice.

I like thinking about it with multiple people to get different views and thoughts on it!

**Comment by Veetaha** [comment]
> I think I prefer `#[builder(on_start_fn)]` to be a bit more clear what is meant from just reading some code of someone else without knowing bon details.

There is already builder(on(...)) attribute where "on" has a bit different meaning (similar to "if" or "when")

So if adding more clarity, I guess `start_fn_arg` works better.

**Comment by ThomasAlban** [comment]
`start_fn_arg` is also fine, if you think the extra characters are worth it for readability. For me, `start_fn` is just as readable, and I think this feature is going to get used quite a lot so any saving on characters is a benefit!

**Comment by EdJoPaTo** [comment]
Why is saving characters a benefit? Autocompletion exists, looking these up and copying will also be done quite often. The output binary size or performance will not be different in any way. We do not need to save characters. The focus should be on readable code, especially when people read code without being familiar with bon.

Thinking about it again, `#[builder(start_fn)]` might actually be enough as the logic here is "related to builder" → "something with the start function on the builder" So I think its probably fine the way it is then.

**Comment by Veetaha** [comment]
> Why is saving characters a benefit

Just pure aesthetics. 

> Autocompletion exists,

Unfortunately not for proc macros. I experimented with some hacks for autocompletion, and they do work, but they don't work at member level (yet), unfortunately. I'll try to fight with that once there is nothing more in priority for `bon`

**Comment by Veetaha** [comment]
Anyway, all of us are biased because we already know how this feature works. In general, I don't think `_arg` suffix makes that big of a difference. I guess people will either need to look up "what the hell is a `start_fn` and `finish_fn`?". So I'd go with the shorter notation

**Review by anelson — APPROVED** [review]

**Comment by Veetaha** [comment]
Done this change was released in a 2.3 version of bon:
- [Reddit post](https://www.reddit.com/r/rust/comments/1fgmbo7/media_nextgen_builder_macro_bon_23_release/)
- [Blog post](https://elastio.github.io/bon/blog/bon-builder-v2-3-release)

**Comment by RGBCube** [comment]
This was merged a while ago, but I actually had to find this to see if positional arguments worked for functions too. It would be great if that example was added to the docs also

**Comment by Veetaha** [comment]
@RGBCube, hi! Thanks for pointing this out. I'm all for improving the docs. Currently, the guide in `bon` [begins](https://bon-rs.com/guide/basics) with this:

> Code examples may use either `fn` or `struct` builder syntax interchangeably. Both follow the same principles unless stated otherwise.

And examples in the [attributes reference](https://bon-rs.com/reference/builder/member/finish_fn) have different "tabs" for different syntax.

image

Basically almost *all* attributes work on all variants of syntax (structs, functions, methods), and I wanted to keep docs shorter and avoid repetitions, so I decided to go with the "tabs" approach in example snippets but only in attributes reference. There could definitely be tabs in the guide section as well, I was just lazy about doing them there because all of them are manually written =)

**Comment by RGBCube** [comment]
Oh, I completely missed that! I was trying to get it done quick and was only skimming the guide itself 😅

I think adding this into the guide would be helpful though, it covers basically everything except this

**Pull request merged**
